version: "2.4"
services:
  mq:
    image: rabbitmq:3.7.19-management-alpine
    networks:
      - demo
    ports:
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "5671:5671"
    environment:
      TZ: "Asia/Shanghai"
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "123456"
    mem_limit: 512MB
  db:
    image: percona:5.7 # 数据库 MySQL 的 Percona 分之发行版
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --ignore-db-dir=lost+found
    networks:
      - demo
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/mysql:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      TZ: "Asia/Shanghai"
    restart: on-failure
    mem_limit: 512MB
  redis:
    image: redis:4.0.14-alpine
    networks:
      - demo
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Shanghai"
    mem_limit: 512MB
  zipkin:
    image: openzipkin/zipkin:2.18.1
    networks:
      - demo
    ports:
      - "9410:9410"
      - "9411:9411"
    environment:
      TZ: "Asia/Shanghai"
      RABBIT_URI: "amqp://rabbit:123456@mq:5672"
    depends_on:
      - mq
networks:
  demo: