version: "2.4"
services:
  hystrix-dashboard:
    image: registry.onetest.newtouch.com/demo/hystrix-dashboard:1.0.0.RELEASE
    networks:
      - demo
    ports:
      - "7703:7703"
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "-Xms128m -Xmx128m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dspring.profiles.active=docker"
    mem_limit: 256MB
    depends_on:
      - mq
    restart: on-failure
  turbine:
    image: registry.onetest.newtouch.com/demo/turbine:1.0.0.RELEASE
    networks:
      - demo
    ports:
      - "7702:7702"
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "-Xms128m -Xmx128m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dspring.profiles.active=docker"
    mem_limit: 256MB
    depends_on:
      - mq
    restart: on-failure
  admin:
    image: registry.onetest.newtouch.com/demo/admin:1.0.0.RELEASE
    networks:
      - demo
    ports:
      - "7701:7701"
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "-Xms128m -Xmx128m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dspring.profiles.active=docker"
    mem_limit: 256MB
    restart: on-failure
  eureka:
    image: registry.onetest.newtouch.com/demo/eureka:1.0.0.RELEASE
    networks:
      - demo
    ports:
      - "8761:8761"
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "-Xms64m -Xmx64m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dspring.profiles.active=docker"
    mem_limit: 128MB
    restart: on-failure
  mq:
    image: rabbitmq:3.7.19-management-alpine
    networks:
      - demo
    ports:
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "5671:5671"
    environment:
      TZ: "Asia/Shanghai"
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "123456"
    mem_limit: 512MB
    restart: on-failure
  db:
    image: percona:5.7 # 数据库 MySQL 的 Percona 发行版
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --ignore-db-dir=lost+found
    networks:
      - demo
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/mysql:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Shanghai"
    mem_limit: 512MB
    restart: on-failure
  oracle:
    image: oracle/database:11.2.0.2-xe
    networks:
      - demo
    ports:
      - "1521:1521"
      - "8000:8080"
    shm_size: 1g
    volumes:
      - "./scripts/oracle:/u01/app/oracle/scripts/startup"
    environment:
      TZ: "Asia/Shanghai"
      ORACLE_PWD: 123456
    mem_limit: 1024MB
    restart: on-failure
  redis:
    image: redis:4.0.14-alpine
    networks:
      - demo
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Shanghai"
    mem_limit: 512MB
    restart: on-failure
  zipkin:
    image: openzipkin/zipkin:2.18.1
    networks:
      - demo
    ports:
      - "9410:9410"
      - "9411:9411"
    environment:
      TZ: "Asia/Shanghai"
      RABBIT_URI: "amqp://rabbit:123456@mq:5672"
    mem_limit: 256MB
    depends_on:
      - mq
    restart: on-failure
networks:
  demo: