spring:
  rabbitmq:
    username: rabbit
    password: 123456
    host: mq
    port: 5672
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
server:
  port: 7702