spring:
  application:
    name: service-gateway
  profiles:
    active: dev

---
spring:
  profiles: dev
  redis:
    host: localhost
    database: 0
    port: 6379
  rabbitmq:
    username: rabbit
    password: 123456
  cloud:
    gateway:
      routes:
        - id: sso_route
          uri: lb://service-auth
          predicates:
            - Path=/api/sso/**
          filters:
            - StripPrefix=2
        - id: organization_route
          uri: lb://service-organization
          predicates:
            - Path=/api/organization/**
          filters:
            - PreOauth2SSOGatewayFilter
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8200
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA04jUUG1yce9wRGyEu7cw22TBsq6opOsSxYi1ck/0ZOKuKDkfyyzLcar6q9lZ0d3SqRPseGrZERaQNVNO88KXs+jvgJunAIeuZF1c2bx1vc/EjIJAdD+F0E1Dg/UzmVVNXEHhpKLqyyLuvqN8lfo3CGrFPG7ii39ib6gSsRemxGLH0Yg+FX9s+UeMJDkjGMg4l3MGBvCOyW/mH6jib5XRo0aefMV9G7jHbbdGnWJmjEcpDO3ds12SZGwQaCt+z453FGuB/Nu+C/o6VYWERg9nVGW4tECQV34NPEAY7NiZcLB2hw2U2T1L6iiQRotFsgvr/ygTfFje4KTIFzj8T23idQIDAQAB
          -----END PUBLIC KEY-----