spring:
  application:
    name: service-gateway
  profiles:
    active: dev

---
spring:
  profiles: dev
  redis:
    host: localhost
    database: 0
    port: 6379
  rabbitmq:
    username: rabbit
    password: 123456
  cloud:
    gateway:
      routes:
        - id: sso_route
          uri: lb://service-auth
          predicates:
            - Path=/api/sso/**
          filters:
            - StripPrefix=2
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8200
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
