CREATE TABLE NEWTOUCH.SYSTEM_USER_INFO
(
    ID CHAR(22) NOT NULL
        PRIMARY KEY,
    NICKNAME VARCHAR2(80) NOT NULL,
    EMAIL VARCHAR2(100) DEFAULT '' NOT NULL,
    CONSTRAINT UNI_SYSTEM_USER_INFO_NICKNAME
        UNIQUE (NICKNAME)
);
COMMENT ON TABLE NEWTOUCH.SYSTEM_USER_INFO IS '系统用户信息';