ALTER TABLE NEWTOUCH.SYSTEM_USER_INFO DROP CONSTRAINT UNI_SYSTEM_USER_INFO_NICKNAME;

ALTER TABLE NEWTOUCH.SYSTEM_USER_INFO ADD USERNAME VARCHAR2(50) DEFAULT '' NOT NULL;

ALTER TABLE NEWTOUCH.SYSTEM_USER_INFO ADD CONSTRAINT UNI_SYSTEM_USER_INFO_NICKNAME UNIQUE (USERNAME);