spring:
  application:
    name: service-corporation
  profiles:
    active: dev

---
spring:
  profiles: dev
server:
  port: 8100
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://service-eureka:8090/eureka/
feign:
  hystrix:
    enabled: true

ribbon:
  eager-load:
    enabled: true

---
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://eureka:8090/eureka/
feign:
  hystrix:
    enabled: true

ribbon:
  eager-load:
    enabled: true