spring:
  application:
    name: service-auth
  profiles:
    active: dev

---
spring:
  profiles: dev
server:
  port: 9999
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://service-eureka:8090/eureka/