eureka:
  instance:
    prefer-ip-address: false
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://cluster01:8761/eureka/
spring:
  devtools:
    remote:
      secret: newtouch # 仅用于开发测试环境，生产环境部署不要配置该属性，置空即可
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: newtouch
    password: 123456
  rabbitmq:
    username: rabbit
    password: 123456
  flyway:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  swagger:
    show: true
server:
  port: 7501
mybatis:
  mapper-locations: classpath:mapper/*.xml