spring:
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
---
spring:
  profiles: dev
  application:
    name: service-admin
  rabbitmq:
    username: rabbit
    password: 123456
  boot:
    admin:
      context-path: /admin
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://registry-server-1:8091/eureka/,http://registry-server-2:8092/eureka/,http://registry-server-3:8093/eureka/
server:
  port: 8300
