server:
  port: 9999
spring:
  devtools:
    remote:
      secret: newtouch # 仅用于开发测试环境，生产环境部署不要配置该属性，置空即可
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_demo_oauth_client?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    username: root
    password: 123456
  rabbitmq:
    username: rabbit
    password: 123456
    host: localhost
  cloud:
    stream:
      bindings:
        user_register:
          destination: demo.user.user_register
          content-type: application/json
          group: userRigsterGroup
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                username: rabbit
                password: 123456
security:
  oauth2:
    authorization:
      jwt:
        key-store: "classpath:jwt.jks"
        key-store-password: www.newtouch.com
        key-alias: jwt
      check-token-access: "isAuthenticated()"
      token-key-access: "permitAll()"
mybatis:
  mapper-locations: classpath:mapper/*.xml
