spring:
  application:
    name: service-zuul
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
zuul.sensitiveHeaders: Cookie,Set-Cookie