spring:
  application:
    name: service-zuul
  profiles:
    active: dev

---
spring:
  profiles: dev
  redis:
    host: localhost
    database: 0
    port: 6379
  rabbitmq:
    username: rabbit
    password: 123456
server:
  port: 7777
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://registry-server-1:8091/eureka/,http://registry-server-2:8092/eureka/,http://registry-server-3:8093/eureka/
ribbon:
  eager-load:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

zuul:
  ignoredServices: '*' # 关闭Zuul自动路由功能（否则会针对Eureka Server中注册的服务自动生成路由）
  routes:
#    api:
#      path: /v1/api/user/**
#      serviceId: service-user
    admin:
      path: /organization/**
      serviceId: service-organization
      stripPrefix: true # 后端服务为网站类型的话，访问Url必须与后端网站的ContextPath一致，否则会导致资源获取路径错误，必须关闭前缀剥离
#    zipkin:
#      path: /zipkin/**
#      url: http://localhost:9411 # 部署时必须指定能解析的zipkin网站域名
#      stripPrefix: false
#    turbine:
#      path: /turbine/**
#      serviceId: service-turbine-ui
#      stripPrefix: false