eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.application.name}:${server.port}/eureka/
server:
  port: 8761