spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: service-eureka
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 15000
server:
  port: 8090
