server:
  port: 7501
spring:
  sleuth:
    sampler:
      percentage: 1.0
  devtools:
    remote:
      secret: newtouch # 仅用于开发测试环境，生产环境部署不要配置该属性，置空即可
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: "jdbc:oracle:thin:@oracle:1521:XE"
    username: newtouch
    password: "{cipher}AQAGo/G3MiqK0xY/GcXES8JXmP+4HuAMi71TEAJOkgGF6ldkhy9+i9i+c5GuKSnmc0RvwdblkwmwFZVnnyQ3BwMlwNFPbphXNG1Zj4CEofRFlWeVewjbyTxs/F31Sb77JPZNSdajs8lnQEwxNZzbopcmASd8SR6rnCJ4V/2bbEblrUmDq9Wi1qjywIkKvi67apWzSLIHevcPDuPGCVnhBgseEGplORByaYccG8JNDNR8tpfkNuaLtKjSNDXMWlbAcBXvDZJaqnjEmhHAYj6FFAAPXKFU4WgAA3yD1dABdqX5y2KKyAy2H8G9X8oTBttuwePd1UhHMSJue3KyPpDf4oMCa3vFHx2tS7sND3wQuPrzaNog53nUWmLI4duAJmN1wgg="
  rabbitmq:
    username: rabbit
    password: "{cipher}AQBdLWSOVRH+18G3ON+xKOCOV41SaUPI5UFSvacL6A3GF+Hb+3BQzNl4EcQNEcdPFkKJgIlo2435pJD5+y3yF37u2dhZ600DMVgJBAc1zqj59x6WubE8/NedT2vD5C+hqdwNw+FVmwdRnms7oLTfXncFHsd+6FekIIReXsmFFJrbHJYi2OQjFASocDLXhO6Zn2PpxqkZ+EtlCVd3FMMHLwDZ/nAsdWon7O4es2FIZ8Vof98SFnuqBn3pKFtYF9uLLcD656pveTZR5PqAddGLsg3ae+lUUW5h5u3t5eBMJaMAjkfz8dJU43Vm4bJPcaCL0nhm2y8TwDtb7hv9VdvzZNycmnXMcRRyOII2oE6YHHxSj2gIdshwgbnZqYVGacoAczk="
    host: mq
  cloud:
    stream:
      bindings:
        user_register:
          destination: demo.user.user_register
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: mq
                username: rabbit
                password: "{cipher}AQBdLWSOVRH+18G3ON+xKOCOV41SaUPI5UFSvacL6A3GF+Hb+3BQzNl4EcQNEcdPFkKJgIlo2435pJD5+y3yF37u2dhZ600DMVgJBAc1zqj59x6WubE8/NedT2vD5C+hqdwNw+FVmwdRnms7oLTfXncFHsd+6FekIIReXsmFFJrbHJYi2OQjFASocDLXhO6Zn2PpxqkZ+EtlCVd3FMMHLwDZ/nAsdWon7O4es2FIZ8Vof98SFnuqBn3pKFtYF9uLLcD656pveTZR5PqAddGLsg3ae+lUUW5h5u3t5eBMJaMAjkfz8dJU43Vm4bJPcaCL0nhm2y8TwDtb7hv9VdvzZNycmnXMcRRyOII2oE6YHHxSj2gIdshwgbnZqYVGacoAczk="
  swagger:
    show: true
security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA04jUUG1yce9wRGyEu7cw22TBsq6opOsSxYi1ck/0ZOKuKDkfyyzLcar6q9lZ0d3SqRPseGrZERaQNVNO88KXs+jvgJunAIeuZF1c2bx1vc/EjIJAdD+F0E1Dg/UzmVVNXEHhpKLqyyLuvqN8lfo3CGrFPG7ii39ib6gSsRemxGLH0Yg+FX9s+UeMJDkjGMg4l3MGBvCOyW/mH6jib5XRo0aefMV9G7jHbbdGnWJmjEcpDO3ds12SZGwQaCt+z453FGuB/Nu+C/o6VYWERg9nVGW4tECQV34NPEAY7NiZcLB2hw2U2T1L6iiQRotFsgvr/ygTfFje4KTIFzj8T23idQIDAQAB
          -----END PUBLIC KEY-----
#        key-uri: http://auth-server:9999/oauth/token_key
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
ribbon:
  eager-load:
    clients: auth-server
    enabled: true