spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LikeSimple/spring-cloud-config
          refresh-rate: 15 # 默认为0，即每次请求都刷新远程信息；否则为指定多久后才刷新
          default-label: master # 指定默认版本，可以是commit id, tag, branch name
          search-paths: {application} # 指定搜索子路径以及搜索格式 repos, {application}/{profile}/{label}
          timeout: 5
#          force-pull: true
#          deleteUntrackedBranches: true
#          clone-on-start: true
#          模板形式
#          repos:
#            development:
#              pattern:
#                - '*/development'
#                - '*/staging'
#              cloneOnStart: true
#              uri: https://github.com/development/config-repo
#              username: trolley
#              password: strongpassword
#              或者也可以使用ssh形式，会使用~/.ssh/下的配置 ，只支持rsa形式，Git服务器应在known_hosts文件中，HTTPS PROXY则配置在~/.git/config中或者使用启动参数-Dhttps.proxyHost and -Dhttps.proxyPort
