spring:
  cloud:
    config.server.native.searchLocations: >
      classpath:/config/organization,
      classpath:/config/zuul
  rabbitmq:
    username: rabbit
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://cluster01:8761/eureka/
server:
  port: 8888