spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        accept-empty: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    user:
      name: demo
      password: demo
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS