spring:
  application:
    name: service-department
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud_demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
server:
  port: 8091
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://service-eureka:8090/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
---
spring:
  profiles: peer1
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/springcloud_demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8092
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://service-eureka:8090/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml

---
spring:
  profiles: peer2
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/springcloud_demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8093
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://service-eureka:8090/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml

---
spring:
  profiles: peer3
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/springcloud_demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8094
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://service-eureka:8090/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml

---
spring:
  profiles: docker
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://db:3306/springcloud_demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://eureka:8090/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml